language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --quiet
  - php composer.phar --version

notifications:
  email:
    - ondrowan@gmail.com
